[package]
name = "Everything"
version = "0.1.0"
description = "A music player"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = ["tray-icon"] }
#tauri-plugin-opener = "2.5.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
rodio = { version = "0.22.2", default-features = false, features = ["playback"] }
symphonia = { version = "0.6.1", default-features = true, features = ["mp3"] }
symphonia-adapter-libopus = "0.3.0"
tauri-plugin-fs = "2.5.1"
log = "0.4.33"
tauri-plugin-log = "2.9.0"
matroska = "0.30.1"

# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

